- hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_network_cli_ssh_type: libssh
    
  tasks:
  - name: run show version command
    ansible.netcommon.cli_command:
      command: show version

  - name: run show interface command
    ansible.netcommon.cli_command:
       command: show interfaces
       

       
       
#
# The Cisco switch must uniquely identify all network-connected endpoint devices before establishing any connection.
#
# https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/sec_usr_8021x/configuration/xe-3se/3850/sec-user-8021x-xe-3se-3850-book/config-ieee-802x-pba.html  
#
#  - name: (V-101165) 802.1x authentication I
#    cisco.ios.ios_config:
#       lines:
#         - aaa new-model 
#         - aaa authentication dot1x default group "{{ method }}"
#         - dot1x system-auth-control  
#    tags:
#    - high
#
#  - name: (V-101165) 802.1x authentication II
#    cisco.ios.ios_config:
#       lines:
#         - dot1x port-control auto
#       parents: '{{ item }}'
#    with_items:
#    - interface Ethernet1
#    - interface Ethernet2
#    - interface GigabitEthernet1
#    tags:
#    - high


#
# The Cisco switch must have all disabled switch ports assigned to an unused VLAN.
#       
#  - name: (V-101205) disabled switch ports assigned to an unused VLAN
#    ansible.netcommon.cli_config:
#       config: "foo" 
#    tags:
#    - medium


#
# The Cisco switch must not have the default VLAN assigned to any host-facing switch ports.
#       
#  - name: (V-101207) not have the default VLAN assigned to any host-facing switch ports
#    ansible.netcommon.cli_config:
#       config: "foo" 
#    tags:
#    - medium


#
# The Cisco switch must have the default VLAN pruned from all trunk ports that do not require it.
#       
#  - name: (V-101209) default VLAN pruned from all trunk ports
#  cisco.ios.ios_l2_interfaces:
#    config:
#    - name: "{{ trunks }}"
#      mode: trunk
#      trunk:
#        allowed_vlans: 10-20,40
#        native_vlan: 20
#        pruning_vlans: "{{ default_vlan }}"
#        encapsulation: dot1q
#    state: merged
#    tags:
#    - medium




