- hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_network_cli_ssh_type: libssh
    
  tasks:
  - name: run show version command
    ansible.netcommon.cli_command:
      command: show version
    register: version  

  - name: run show interface command
    ansible.netcommon.cli_command:
       command: show interfaces
    register: interfaces
       
  - debug: var=version 
  - debug: var=interfaces
       
